version: '3'
services:
#name the container
  react-app:
#tell docker where to build from, context of the current directory, and 
#specifically look for the file named 'Dockerfile.dev' since it typically
#looks for 'Dockerfile'
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "8080:3000"
#do not map the /app/node_modules folder from the container with anything
#local 
#map the pwd of the local directory to the /app folder in the container
    volumes:
      - /app/node_modules
      - .:/app 

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command:
      ["npm", "run", "test"]
    